import type { EdgeCase } from './edgeCaseCoverage'

export const EDGE_CASES: readonly EdgeCase[] = [
  {
    id: 'EC-band-low',
    area: 'audio',
    summary: 'Frequencies below 25 Hz are not published',
    testFile: 'src/audio/pitchDetector.test.ts',
  },
  {
    id: 'EC-band-high',
    area: 'audio',
    summary: 'Frequencies above 1000 Hz are not published',
    testFile: 'src/audio/pitchDetector.test.ts',
  },
  {
    id: 'EC-rms-floor',
    area: 'audio',
    summary: 'Bass needs a higher RMS floor than guitar',
    testFile: 'src/audio/pitchDetector.test.ts',
  },
  {
    id: 'EC-hum-rms',
    area: 'audio',
    summary: 'Quiet low-frequency hum is rejected',
    testFile: 'src/audio/pitchDetector.test.ts',
  },
  {
    id: 'EC-clarity',
    area: 'audio',
    summary: 'Clarity floor is stricter above 100 Hz',
    testFile: 'src/audio/pitchDetector.test.ts',
  },
  {
    id: 'EC-dc',
    area: 'audio',
    summary: 'DC bias is removed before detection',
    testFile: 'src/audio/pitchDetector.test.ts',
  },
  {
    id: 'EC-confirm-3',
    area: 'audio',
    summary: 'A pitch is published only after three agreeing windows',
    testFile: 'src/audio/micWindowHandler.test.ts',
  },
  {
    id: 'EC-jump-150',
    area: 'audio',
    summary: 'A jump above 150 cents clears the median history',
    testFile: 'src/audio/micWindowHandler.test.ts',
  },
  {
    id: 'EC-suppress-clear',
    area: 'audio',
    summary: 'Reference-tone suppression blanks a frozen pitch',
    testFile: 'src/audio/micWindowHandler.test.ts',
  },
  {
    id: 'EC-suppress-window',
    area: 'audio',
    summary: 'Suppression lasts for the requested duration and can be extended',
    testFile: 'src/audio/pitchGate.test.ts',
  },
  {
    id: 'EC-highpass-bass',
    area: 'audio',
    summary: 'Reference highpass sits below five-string bass B0',
    testFile: 'src/audio/referenceTone.test.ts',
  },
  {
    id: 'EC-security-denied',
    area: 'audio',
    summary: 'SecurityError is reported as permission denied',
    testFile: 'src/audio/micStream.test.ts',
  },
  {
    id: 'EC-not-readable',
    area: 'audio',
    summary: 'A busy microphone is reported as unavailable',
    testFile: 'src/audio/micStream.test.ts',
  },
  {
    id: 'EC-hidden-ended',
    area: 'audio',
    summary: 'A track ending in the background does not restart the mic',
    testFile: 'src/audio/micStream.test.ts',
  },
  {
    id: 'EC-stale-start',
    area: 'audio',
    summary: 'An older start cannot replace a newer mic session',
    testFile: 'src/audio/micSessionControl.test.ts',
  },
  {
    id: 'EC-resume-timeout',
    area: 'audio',
    summary: 'A resume that never settles is a failure',
    testFile: 'src/audio/audioContextResume.test.ts',
  },
  {
    id: 'EC-stale-30s',
    area: 'audio',
    summary: 'Background longer than 30s rebuilds the mic session',
    testFile: 'src/audio/useMicControls.test.ts',
  },
  {
    id: 'EC-bfcache',
    area: 'audio',
    summary: 'A persisted pageshow counts as an unknown, stale background',
    testFile: 'src/audio/appResume.test.ts',
  },
  {
    id: 'EC-intune-5',
    area: 'tuning',
    summary: '5 cents is in tune and 6 cents is not',
    testFile: 'src/core/tunings/analyzer.test.ts',
  },
  {
    id: 'EC-tie-first',
    area: 'tuning',
    summary: 'Equal targets keep the earlier string',
    testFile: 'src/core/tunings/analyzer.test.ts',
  },
  {
    id: 'EC-open-c-unison',
    area: 'tuning',
    summary: 'Open C auto-selects the first of two G4 strings',
    testFile: 'src/core/tunings/analyzer.test.ts',
  },
  {
    id: 'EC-octave-apart',
    area: 'tuning',
    summary: 'Standard guitar low E and high E stay distinct',
    testFile: 'src/core/tunings/analyzer.test.ts',
  },
  {
    id: 'EC-high-g',
    area: 'tuning',
    summary: 'Reentrant ukulele High G matches the G string',
    testFile: 'src/core/tunings/analyzer.test.ts',
  },
  {
    id: 'EC-empty-tuning',
    area: 'tuning',
    summary: 'A tuning with no strings has no analysis',
    testFile: 'src/core/tunings/analyzer.test.ts',
  },
  {
    id: 'EC-manual-oor',
    area: 'tuning',
    summary: 'A manual index past the string list is null',
    testFile: 'src/core/tunings/analyzer.test.ts',
  },
  {
    id: 'EC-manual-far',
    area: 'tuning',
    summary: 'Manual mode still reports cents when the note is far away',
    testFile: 'src/core/tunings/analyzer.test.ts',
  },
  {
    id: 'EC-chromatic-boundary',
    area: 'tuning',
    summary: 'Chromatic mode picks the nearer semitone',
    testFile: 'src/core/tunings/analyzer.test.ts',
  },
  {
    id: 'EC-a440',
    area: 'music',
    summary: 'A4 is 440 Hz',
    testFile: 'src/core/music/frequency.test.ts',
  },
  {
    id: 'EC-bad-note',
    area: 'music',
    summary: 'Only the twelve sharp note names are stored',
    testFile: 'src/storage/customTuningsStore.test.ts',
  },
  {
    id: 'EC-lock-2',
    area: 'signal',
    summary: 'The needle latches after two in-tune readings',
    testFile: 'src/core/signal/pitchStabilizer.test.ts',
  },
  {
    id: 'EC-attack-sharp',
    area: 'signal',
    summary: 'A sharp attack is damped',
    testFile: 'src/core/signal/pitchStabilizer.test.ts',
  },
  {
    id: 'EC-attack-flat',
    area: 'signal',
    summary: 'A flat attack is shown in full',
    testFile: 'src/core/signal/pitchStabilizer.test.ts',
  },
  {
    id: 'EC-unlock-14',
    area: 'signal',
    summary: 'A latched needle holds 14 cents and releases at 15',
    testFile: 'src/core/signal/pitchStabilizer.test.ts',
  },
  {
    id: 'EC-decay-latch',
    area: 'state',
    summary: 'A dropout clears the needle and a quick return keeps the latch',
    testFile: 'src/state/useStableAnalysis.test.ts',
  },
  {
    id: 'EC-scope-reset',
    area: 'state',
    summary: 'Changing tuning scope clears the latch',
    testFile: 'src/state/useStableAnalysis.test.ts',
  },
  {
    id: 'EC-chromatic-live',
    area: 'state',
    summary: 'Chromatic cents are not latched',
    testFile: 'src/state/useStableAnalysis.test.ts',
  },
  {
    id: 'EC-gauge-clamp',
    area: 'ui',
    summary: 'The needle stops at ±50 cents',
    testFile: 'src/components/TunerGauge.test.tsx',
  },
  {
    id: 'EC-gauge-center',
    area: 'ui',
    summary: 'An in-tune string centers the needle',
    testFile: 'src/App.gauge.test.tsx',
  },
  {
    id: 'EC-hint-round',
    area: 'ui',
    summary: 'Chromatic hint rounds cents independently of the in-tune cut',
    testFile: 'src/components/TuneDirectionHint.test.tsx',
  },
  {
    id: 'EC-octave-picker',
    area: 'ui',
    summary: 'The note picker offers octaves 0 through 6',
    testFile: 'src/components/NotePicker.test.tsx',
  },
  {
    id: 'EC-rail-slop',
    area: 'ui',
    summary: 'A 1px string-rail sliver is not overflow',
    testFile: 'src/components/stringRailOverflow.test.ts',
  },
  {
    id: 'EC-install-native',
    area: 'ui',
    summary: 'The install hint stays hidden in the native shell',
    testFile: 'src/components/InstallHint.test.tsx',
  },
  {
    id: 'EC-blank-save',
    area: 'storage',
    summary: 'A blank draft name is not saved',
    testFile: 'src/state/customTuningActions.test.ts',
  },
  {
    id: 'EC-blank-rename',
    area: 'storage',
    summary: 'A blank rename is ignored',
    testFile: 'src/components/CustomTuningList.test.tsx',
  },
  {
    id: 'EC-partial-string',
    area: 'storage',
    summary: 'One bad string is dropped and the others are kept',
    testFile: 'src/storage/customTuningsStore.test.ts',
  },
  {
    id: 'EC-unknown-instrument',
    area: 'storage',
    summary: 'An unknown instrument drops the tuning',
    testFile: 'src/storage/customTuningsStore.test.ts',
  },
  {
    id: 'EC-corrupt-json',
    area: 'storage',
    summary: 'Corrupt storage reads as an empty list',
    testFile: 'src/storage/customTuningsStore.test.ts',
  },
  {
    id: 'EC-quota',
    area: 'storage',
    summary: 'A storage quota error does not throw',
    testFile: 'src/storage/customTuningsStore.test.ts',
  },
  {
    id: 'EC-legacy-delete',
    area: 'storage',
    summary: 'Deleting a tuning removes it from legacy keys too',
    testFile: 'src/storage/customTuningsStore.test.ts',
  },
  {
    id: 'EC-dedupe',
    area: 'storage',
    summary: 'Identical name and pitches collapse to one saved tuning',
    testFile: 'src/storage/customTuningsStore.test.ts',
  },
  {
    id: 'EC-unique-id',
    area: 'storage',
    summary: 'Two saves in the same millisecond get different ids',
    testFile: 'src/storage/customTuningsStore.test.ts',
  },
  {
    id: 'EC-draft-hidden',
    area: 'tuning',
    summary: 'A draft is not listed in My tunings',
    testFile: 'src/core/tunings/custom.test.ts',
  },
  {
    id: 'EC-manual-wkwebview',
    area: 'native',
    summary: 'WKWebView may deliver silent mic samples while iOS is capturing',
    testFile: null,
    reason: 'Needs a physical iPhone; the simulator does not reproduce it',
  },
  {
    id: 'EC-manual-silent-switch',
    area: 'native',
    summary: 'The hardware silent switch mutes tones on iOS before audioSession',
    testFile: null,
    reason: 'Depends on the hardware ring switch and an iOS version before 17',
  },
  {
    id: 'EC-manual-itp',
    area: 'storage',
    summary: 'Safari may evict site storage after about seven days away',
    testFile: null,
    reason: 'Browser storage eviction cannot be reproduced in unit tests',
  },
  {
    id: 'EC-manual-bt-voice',
    area: 'audio',
    summary: 'A headset voice profile can still filter bass despite the mic flags',
    testFile: null,
    reason: 'The OS voice path is outside the Web Audio constraint flags',
  },
  {
    id: 'EC-manual-phone-call',
    area: 'audio',
    summary: 'A carrier call takes the microphone away from the tuner',
    testFile: null,
    reason: 'Needs a device radio interruption',
  },
]
